version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "758808000904"
    AWS_DEFAULT_REGION: "us-east-1"
    IMAGE_REPO_NAME: "cicd_web_page"

version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - AWS_REGION=$AWS_DEFAULT_REGION
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Account ID: $AWS_ACCOUNT_ID
      - echo Region: $AWS_REGION
      - echo ECR URI: $ECR_URI
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo Building Docker image
      - docker build -t devops-web .
      - docker tag devops-web:latest $ECR_URI/devops-web:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR
      - docker push $ECR_URI/devops-web:latest
      - echo Docker image pushed successfully
